### ISSUE TITLE
add Zenodo module to the EPFL version

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/roc-eln-docker#18]
I guess this would be quite useful and a "selling point".

**Comment by lpatiny** [comment]
Actually it is already there but with limited access. 

It is also submission to the sandbox but currently it does not work. Not sure if it is the sanbox the problem or a change in the API.

**Comment by lpatiny** [comment]
@kjappelbaum I added your on eln.epfl.ch so that you see the button and can make demo

**Comment by kjappelbaum** [comment]
Thanks, I can put on my todo list to check why it does not work.
