### ISSUE TITLE
roc-eln-docker/roc-config.js

### ISSUE THREAD

**Issue by andcastillo** [cheminfo/roc-eln-docker#2]
What is supposed not to be changed should not be in the config. There should be a shorter .json with the real configuration parameters.

**Comment by targos** [comment]
This technically not possible due to how rest-on-couch loads the config. I think it's a matter of documentation and I added comments in the sample file.
What we can do is put the variable parameters at the beginning of the file and the fixed ones below with a comment to explain they cannot change.
