### ISSUE TITLE
How to save home-view?

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/roc-eln-docker#20]
Hi and sorry for the many issues I open here---I'm still trying to familiarize myself with the visualizer. 

I'm trying to change the tiles that are shown on the home page but I have found no way to persist the changes i make in the `Links` layer (other than manually changing the `home-view.json`).

Is there a way in which I can directly do it from the visualizer? 

![Screen Shot 2020-07-13 at 14 26 56](https://user-images.githubusercontent.com/32935233/87304980-04e09180-c516-11ea-96a3-a670bf24da0d.png)

**Comment by lpatiny** [comment]
This should help: https://github.com/cheminfo/roc-eln-docker/blob/master/faq.md#how-to-edit-homepage

**Comment by kjappelbaum** [comment]
Great, thanks! so much to learn ...

I didn't dig deeper from there as the initial page that loaded for /on-tabs was empty
