### ISSUE TITLE
allow to customize page titles

### ISSUE THREAD

**Issue by targos** [cheminfo/roc-eln-docker#3]
Currently it defaults to `visualizer-on-tabs`.
@stropitek does it need changes to the flavor-builder?

**Comment by stropitek** [comment]
It would need changes to visualizer-on-tabs

**Comment by targos** [comment]
https://github.com/cheminfo/visualizer-on-tabs/commit/48b2da955eeb3b26faa7d1f6f934239b87fa60ec
